baseurl = "http://grimrose.github.io/blog"
languageCode = "ja"
title = "open build/reports/life/index.html"

canonifyurls = true
builddrafts = false
paginate = 10

[indexes]
  category = "categories"
  tag = "tags"
[permalinks]
  posts = "/:year/:month/:slug/"

[params]
  project   = "blog"
  description = "Life Weblog"
  logo      = "assets/images/logo.jpg"
  twitter   = "https://twitter.com/grimrose"
  github    = "https://github.com/grimrose/"
  homeUrl   = "http://grimrose.github.io/"
