version: "3"

services:
  hugo:
    build: .
    ports:
      - "1313:1313"
    expose:
      - 1313
    volumes:
      - "./:/src"
    command: "server -w --bind 0.0.0.0"
    networks:
      - blog_net

networks:
  blog_net:
